### ISSUE TITLE
Does this extension change the name of the fields?

### ISSUE THREAD

**Issue by marwan-nwh** [ericlackey/netsuite-field-finder#28]
Hi,

We had a strange issue today, in saved searches built on top of invoices for example, the customer related record is always called `Customer fields...`, our client didn't find it, and after searching, we found it was renamed to `Cliente fields...`.

This image shows the problem:
<img width="688" alt="Screenshot 2023-10-23 180248" src="https://github.com/ericlackey/netsuite-field-finder/assets/1739939/4f792b83-e13f-4ace-8ffa-bae098add2ec">

These two show that other fields weren't affected:
<img width="608" alt="Screenshot 2023-10-23 181238" src="https://github.com/ericlackey/netsuite-field-finder/assets/1739939/b6c9c696-3bd4-4c49-b4cb-1f523199bb88">
<img width="311" alt="Screenshot 2023-10-23 181227" src="https://github.com/ericlackey/netsuite-field-finder/assets/1739939/e2f40215-9004-4681-a9a2-26a605016e70">

Disabling the extension solved the problem. 
**Also, after enabling the extension again, the issue didn't occur again.** 
<img width="635" alt="image" src="https://github.com/ericlackey/netsuite-field-finder/assets/1739939/841053df-1961-4357-92dd-98c01d6c331e">

**Comment by ericlackey** [comment]
This is pretty strange. This extension accesses the NetSuite dropdown object returned from NetSuite and makes modifications to things like field names and HTML elements. But, it does not do anything like change the language of the field name. I can't yet explain how the field language is being changed. It seems like those field name values must be coming from NetSuite. But, that doesn't explain why disabling and re-enabling the extension would have resolved it.
