### ISSUE TITLE
Joined Field Issues

### ISSUE THREAD

**Issue by JaredUHS** [ericlackey/netsuite-field-finder#42]
Hi,

Ever since a few days ago (I am assuming after NetSuite's latest update on our account), joined fields no longer work.

What is happening is when on an item saved search and trying to add a transaction join or on a transaction search adding an item join, it commits the line but does not let me save & run or move it around as it says "Please enter a value for Field", same with filters.

**Comment by jeff282** [comment]
I am experiencing the exact same issue, removing or disabling the extension allows the search to execute.

**Comment by ericlackey** [comment]
@jeff282  @JaredUHS  Thank you so much! I think I have figured out what's going on here.

**Comment by ericlackey** [comment]
@jeff282 @JaredUHS  This should be fixed in 0.27. Thanks again.

**Comment by jeff282** [comment]
@ericlackey I appear to be having the same issue on .27 for the results tab.

**Comment by ericlackey** [comment]
@jeff282  That is weird. I'm not seeing it anymore. Are you able to send me a screenshot of the error along with any errors you see in the console? Thanks

**Comment by jeff282** [comment]
Hey @ericlackey it appears to throw an error in console at the exact moment I hit add to the joined field line. It will execute a search with existing joined fields, just not new ones. 

Let me know if any further info would help!

![CleanShot 2024-01-31 at 09 21 46](https://github.com/ericlackey/netsuite-field-finder/assets/130023634/5c9b6d73-e99b-4446-a897-a574c27f04dc)

![CleanShot 2024-01-31 at 09 21 20](https://github.com/ericlackey/netsuite-field-finder/assets/130023634/a4ae2f7e-ff5c-46de-a176-1b5ebb53ecd3)

**Comment by ericlackey** [comment]
@jeff282 Thanks for sticking with me. I've just released another version 0.28. Could you try this one and let me know how it goes?
